name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to droplet
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        script: |
          # Ensure project directory exists
          mkdir -p /opt/medical-project
          cd /opt/medical-project
          
          # Clean up and get fresh code
          rm -rf MProject
          git clone https://github.com/4747uwu/MProject.git
          
          # Navigate to the MedicalProject subdirectory
          cd MProject/MedicalProject
          
          # ✅ UPDATED: Create production environment file with LOCAL MongoDB
          cat > .env << 'EOF'
          NODE_ENV=production
          MONGODB_URI=mongodb://alice:alicePassword@64.227.187.164:27017/medicalproject
          REDIS_URL=rediss://default:ATDmAAIjcDFlY2U3MzZmZjIxNDQ0YmZmYmY0NmVlZTBhMjgwOTkyYnAxMA@just-pug-12518.upstash.io:6379
          JWT_SECRET=your_jwt_secret_for_day_2_auth
          SMTP_HOST=smtp.gmail.com
          SMTP_PORT=587
          SMTP_USER=pawrangerskyler@gmail.com
          SMTP_PASS=cnuw_zttj_vzsx_dbxh
          SENDER_EMAIL=pawrangerskyler@gmail.com
          WASABI_ACCESS_KEY=EMJYIRHNX3687Z1HDF9R
          WASABI_SECRET_KEY=n2ZP0zoTSCOmQ5vo20zteAQGcg9XNjO7br4idAOe
          WASABI_REGION=ap-southeast-1
          WASABI_ENDPOINT=https://s3.ap-southeast-1.wasabisys.com
          WASABI_DICOM_BUCKET=diacom
          WASABI_DOCUMENTS_BUCKET=medicaldocuments
          WASABI_REPORTS_BUCKET=diacomreports
          WASABI_BACKUPS_BUCKET=medical-backups
          EOF
          
          # ✅ SAFE: Only stop our project containers (preserve Orthanc/OHIF/MongoDB)
          echo "=== Gentle cleanup ==="
          docker-compose -f docker-compose.prod.yml stop backend frontend 2>/dev/null || echo "No existing project containers to stop"
          docker-compose -f docker-compose.prod.yml rm -f backend frontend 2>/dev/null || echo "No existing project containers to remove"
          
          # Build only backend and frontend
          echo "=== Building backend and frontend ==="
          if ! docker-compose -f docker-compose.prod.yml build --no-cache backend frontend; then
            echo "❌ Build failed! Checking logs..."
            docker-compose -f docker-compose.prod.yml logs backend frontend
            exit 1
          fi
          
          # Start only backend and frontend (skip Orthanc since it's already running)
          echo "=== Starting backend and frontend ==="
          if ! docker-compose -f docker-compose.prod.yml up -d backend frontend; then
            echo "❌ Container startup failed! Checking logs..."
            docker-compose -f docker-compose.prod.yml logs backend frontend
            exit 1
          fi
          
          # Wait for containers to start
          sleep 15
          
          # Show all running containers
          echo "=== All Running Containers ==="
          docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"
          
          # Check our project containers specifically
          echo "=== Medical Project Status ==="
          docker-compose -f docker-compose.prod.yml ps backend frontend
          
          # Check logs for any errors
          echo "=== Recent Container Logs ==="
          docker-compose -f docker-compose.prod.yml logs --tail=50 backend frontend
          
          # Install and check ports
          apt update && apt install -y net-tools
          echo "=== Listening Ports ==="
          netstat -tlnp | grep -E ':(80|3000|4000|8042|27017)' || echo "No services listening on target ports"
          
          # Clean up old images
          docker image prune -f
          
          echo "✅ Deployment complete! Preserved: Orthanc, OHIF, MongoDB"