name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to droplet
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        script: |
          # Navigate to project directory
          cd /opt/medical-project
          
          # Clean up and get fresh code
          rm -rf MProject
          git clone https://github.com/4747uwu/MProject.git
          
          # Navigate to the MedicalProject subdirectory
          cd MProject/MedicalProject
          
          # Create production environment file
          cat > .env << 'EOF'
          NODE_ENV=production
          MONGODB_URI=mongodb+srv://4747uwu:fitkymA4NsAHdNoM@cluster0.lr1ko.mongodb.net/medicalproject?retryWrites=true&w=majority
          REDIS_URL=rediss://default:ATDmAAIjcDFlY2U3MzZmZjIxNDQ0YmZmYmY0NmVlZTBhMjgwOTkyYnAxMA@just-pug-12518.upstash.io:6379
          JWT_SECRET=your_jwt_secret_for_day_2_auth
          SMTP_HOST=smtp.gmail.com
          SMTP_PORT=587
          SMTP_USER=pawrangerskyler@gmail.com
          SMTP_PASS=cnuw_zttj_vzsx_dbxh
          SENDER_EMAIL=pawrangerskyler@gmail.com
          WASABI_ACCESS_KEY=EMJYIRHNX3687Z1HDF9R
          WASABI_SECRET_KEY=n2ZP0zoTSCOmQ5vo20zteAQGcg9XNjO7br4idAOe
          WASABI_REGION=ap-southeast-1
          WASABI_ENDPOINT=https://s3.ap-southeast-1.wasabisys.com
          WASABI_DICOM_BUCKET=diacom
          WASABI_DOCUMENTS_BUCKET=medicaldocuments
          WASABI_REPORTS_BUCKET=diacomreports
          WASABI_BACKUPS_BUCKET=medical-backups
          EOF
          
          # Stop existing containers
          docker-compose -f docker-compose.prod.yml down || true
          
          # Build with error checking
          echo "=== Building containers ==="
          if ! docker-compose -f docker-compose.prod.yml build --no-cache; then
            echo "❌ Build failed! Checking logs..."
            docker-compose -f docker-compose.prod.yml logs
            exit 1
          fi
          
          # Deploy with error checking
          echo "=== Starting containers ==="
          if ! docker-compose -f docker-compose.prod.yml up -d; then
            echo "❌ Container startup failed! Checking logs..."
            docker-compose -f docker-compose.prod.yml logs
            exit 1
          fi
          
          # Wait for containers to start
          sleep 15
          
          # Check container status with detailed info
          echo "=== Container Status ==="
          docker-compose -f docker-compose.prod.yml ps
          
          echo "=== All Docker Containers ==="
          docker ps -a
          
          # Check logs for any errors
          echo "=== Recent Container Logs ==="
          docker-compose -f docker-compose.prod.yml logs --tail=50
          
          # Install and check ports
          apt update && apt install -y net-tools
          echo "=== Listening Ports ==="
          netstat -tlnp | grep -E ':(80|3000|8042)' || echo "No services listening on target ports"
          
          # Check if containers are actually healthy
          echo "=== Container Health ==="
          for container in $(docker-compose -f docker-compose.prod.yml ps -q); do
            echo "Container: $container"
            docker inspect $container | grep -A 5 "Health\|State" || echo "No health info"
          done
          
          # Clean up old images
          docker image prune -f